# Generated by Django 4.2.7 on 2023-11-20 10:08

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="pub_date", new_name="pub_dttm",
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                max_length=100, validators=[blog.models.validate_charfield_not_empty]
            ),
        ),
    ]
