# Generated by Django 4.2.7 on 2023-11-20 10:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_pub_date_article_pub_dttm_alter_article_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "content",
                    models.TextField(
                    ),
                ),
                ("pub_dttm", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
