# Generated by Django 4.2.7 on 2023-11-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
