# Generated by Django 4.2.7 on 2023-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="title", field=models.CharField(max_length=100),
        ),
    ]
